# Generated by Django 5.2.10 on 2026-01-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sprite_icon', models.URLField(blank=True, max_length=500, null=True)),
                ('sprite_animated', models.URLField(blank=True, max_length=500, null=True)),
                ('sprite_hd', models.URLField(blank=True, max_length=500, null=True)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('total', models.IntegerField(default=0)),
                ('type_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
