# Generated by Django 5.2.10 on 2026-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('pp', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('target', models.CharField(max_length=50)),
                ('effect_chance', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('mechanics', models.JSONField(default=dict)),
            ],
        ),
    ]
